### ISSUE TITLE
stpyfits incompatible with Astropy 3.2

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#98]
This is most probably caused by astropy/astropy#8502 . In `stpyfits`, it inherits `_ImageBaseHDU` and then assumes the header has a `copy()` method, which is no longer true.

https://github.com/spacetelescope/stsci.tools/blob/b926e11b4f1afa09fe7cf6b7893ebf2a54182c94/lib/stsci/tools/stpyfits.py#L69-L82

I think the fix here is to force the header to not lazy load (diligent load?) first before doing the copy.

Example failure log: https://travis-ci.org/spacetelescope/stsci.tools/jobs/543835788

**Comment by saimn** [comment]
With the new version in Astropy the header is not supposed to be modified at this stage. Because when instantiating the HDU object, the full header has not yet been parsed, only a minimal header has been parsed for the HDUs creation.
So one possible solution could be to delay the stuff done here to when the full header is loaded, which could possibly be done by overriding the `_DelayedHeader` descriptor (more specifically its `__get__` method).
Another option could be to do this manually, moving the code to a "modify_header" method which would be called once when `header` or `data` is called.
